### PR TITLE
#92 - small fixes to main page

### LINKED ISSUE #92: Fix small issues regarding main page
- [x] 1.Unnecessary else statement in functions.js
- [x] 2.Revert to arrow function
- [x] 3.Function in FilterContent can be rewritten to use Vue instead of jquery

### PR DESCRIPTION
**Pull request by brzozka**
This PR should close #92 

As in title. Fixed previous problems/suggested changes regarding main page.

### CODE REVIEW

**Review by kamilpiech97 — DISMISSED** [review]

**Review by EwelinaLasowy — DISMISSED** [review]

**Review by plencka — DISMISSED** [review]

**Review by EwelinaLasowy — APPROVED** [review]

**Review by plencka — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

File: frontend/components/FilterContent.vue [hunk 1]
```diff
@@ -85,29 +97,12 @@ export default {
...
-          }
-        } else {
-          arr.push(tags[i].firstElementChild.innerText);
-        }
-        tags[i].classList.toggle("highlight");
-      });
-    }
     this.eventBus.on("reset", function (reset) {
       if (reset) {
         let high = document.querySelectorAll(".highlight");
```
Comment (gLenczuk) [inline frontend/components/FilterContent.vue:102]: Why `querySelector` and other native JS methods are used? Since you're using Vue it's antipattern.

You can just clear `activeTags` array, and create computed property which checks if tag is in this array, if it's true, apply one class, if not, apply other.

**Review by gLenczuk — CHANGES_REQUESTED** [review]
