### PR TITLE
#122 - navbar funcionality fixed

### LINKED ISSUE #122: Additional `jump to` button on the `home` page
Screenshot from 2021-08-11 14 01 03

I don't seem to be able to return to the landing page. 

I expected the logo/`Znajdź praktyki` button to lead me there, which is common behavior on other websites.
Instead, it jumps to the top of the page, possibly the map section.

I think we should include current logo button functionality in new button called `Mapa firm [eng. Company map]`, and logo itself should return to the landing.

### PR DESCRIPTION
**Pull request by brzozka**
This PR should close #122 

Added new component to navbar named Mapa firm that works as our previous logo button. Now logo button redirects user to Landing page after clicking.

### CODE REVIEW

File: frontend/components/Nav.vue [hunk 1]
```diff
@@ -4,13 +4,29 @@
       <div class="flex justify-between h-16">
         <div class="flex">
           <div class="noselect flex-shrink-0 flex items-center">
-            <router-link to="/home">
-              <a class="logo noselect" title="Home" @click="goHome()"
-                >Znajdź Praktyki</a
-              >
+            <router-link to="/">
+              <a class="logo noselect" title="Home">Znajdź Praktyki</a>
             </router-link>
```
Comment (gLenczuk) [inline frontend/components/Nav.vue:9]: Why do u need `<a>` inside `router-link`? It's redundant.

**Review by gLenczuk — CHANGES_REQUESTED** [review]

File: frontend/components/Nav.vue (hunk 1 above)
Comment (brzozka) [reply frontend/components/Nav.vue:9]: Oh yeah, it wasn't coded by me so I didn't pay attention to that. I will change it, thanks!

**Review by EwelinaLasowy — APPROVED** [review]

**Review by gLenczuk — APPROVED** [review]

**Review by plencka — APPROVED** [review]
