### PR TITLE
#40 - custom exception implementation

### LINKED ISSUE #40: Custom Exception Implementation.
Sometimes script will encounter issue which needs attention, like invalid data set. We should implement exceptions to specify expected values and throw error when they are invalid.

### PR DESCRIPTION
**Pull request by plencka**
It should close #40.
I honestly have no idea how to properly do exceptions yet, so I hope I didn't butcher it too much.

Most exceptions aren't handled, as I don't see a way to do that without whole build failing. Unless we want to [for example] skip companies that have invalid data and inform on build that they need fixing.

### CODE REVIEW

File: backend/Exceptions/File/NoNameFileException.php [hunk 1]
```diff
@@ -0,0 +1,13 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Internships\Exceptions\File;
+
+class NoNameFileException extends FileException
```
Comment (kamilpiech97) [inline backend/Exceptions/File/NoNameFileException.php:7]: I think that in all exception classes you should add http codes e.g. 422, 404 etc.
U can choose which type of code will be okey - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

File: backend/Exceptions/File/FileException.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+namespace Internships\Exceptions\File;
+
+use Internships\Exceptions\SimpleMessageException;
+use Throwable;
+
+class FileException extends SimpleMessageException
+{
+    protected string $fullPath;
+    protected string $fileName;
```
Comment (kamilpiech97) [inline backend/Exceptions/File/FileException.php:13]: Where is this variable used? 
`protected string $fileName;`

Comment (plencka) [reply backend/Exceptions/File/FileException.php:13]: Oh, it's little leftover. Before I wanted to have path and filename separate, then I noticed that filename itself can be included with path.
Already removed in my local branch. I'll push with status code change.

File: backend/Exceptions/File/NoNameFileException.php (hunk 1 above)
Comment (plencka) [reply backend/Exceptions/File/NoNameFileException.php:7]: It's static site and they won't be thrown at site's runtime. However, I think it's good idea to include them for simplified information and possible further development.

File: backend/Exceptions/Validation/ValidationException.php [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    }
+
+    protected function newExceptionMessage(): string
+    {
+        return "There was trouble validating {$this->fieldName} field in ID:{$this->entryID}";
+    }
+
+    protected function getStatusCode(): int
+    {
+        return static::INTERNAL_SERVER_ERROR;
```
Comment (kamilpiech97) [inline backend/Exceptions/Validation/ValidationException.php:29]: If you validating some data and validate gone wrong, your response code will be 422 (Unprocessable Entity) - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422.

File: backend/Exceptions/Path/PathException.php [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+    }
+
+    protected function newExceptionMessage(): string
+    {
+        return "There was trouble processing path {$this->fullPath}.";
+    }
+
+    protected function getStatusCode(): int
+    {
+        return static::INTERNAL_SERVER_ERROR;
```
Comment (kamilpiech97) [inline backend/Exceptions/Path/PathException.php:27]: You will change this response code.
If u return code 500, u said:
- overloading the server with the number of queries,
- script error,
- error in the .htaccess file,
- incorrect file access level setting.

File: backend/Exceptions/File/FileException.php [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+    }
+
+    protected function newExceptionMessage(): string
+    {
+        return "There was trouble processing file at {$this->fullPath}.";
+    }
+
+    protected function getStatusCode(): int
+    {
+        return static::INTERNAL_SERVER_ERROR;
```
Comment (kamilpiech97) [inline backend/Exceptions/File/FileException.php:27]: Change this code 500. Information in comment below.

**Review by kamilpiech97 — COMMENTED** [review]
I have one question about empty files in backend/Models/*.php 
You have in this PR six files like that.

File: backend/Exceptions/File/CsvInvalidCountFileException.php [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+    ) {
+        $this->lineNumber = $lineNumber;
+        $this->expectedCount = $expectedCount;
+        $this->receivedCount = $receivedCount;
+        parent::__construct(
+            $fullPath,
+            $code,
+            $previous
+        );
+    }
```
Comment (mtracz) [inline backend/Exceptions/File/CsvInvalidCountFileException.php:31]: Maybe use constructor promotion?
https://stitcher.io/blog/constructor-promotion-in-php-8

File: backend/Exceptions/SimpleMessageException.php [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+
+class SimpleMessageException extends Exception
+{
+    protected const BAD_REQUEST = 400;
+    protected const METHOD_NOT_ALLOWED = 405;
+    protected const FORBIDDEN = 403;
+    protected const NOT_FOUND = 404;
+    protected const RANGE_NOT_SATISFIABLE = 416;
+    protected const IM_A_TEAPOT = 418;
+    protected const INTERNAL_SERVER_ERROR = 500;
```
Comment (mtracz) [inline backend/Exceptions/SimpleMessageException.php:19]: I am not sure that HTTP response codes will be useful there. Maybe let's create own error codes? Users won't execute this script themselfs so, these error codes should be usefull for developers, who will mantain this app.

**Review by mtracz — CHANGES_REQUESTED** [review]

**Comment by plencka** [comment]
> I have one question about empty files in backend/Models/*.php
> You have in this PR six files like that.

I cannot seem to be able to respond directly to this comment, @kamilpiech97.
It seems those files aren't empty, just the changes aren't present in the file content itself. They probably were committed due to me elevating some other files and I didn't notice that command also affected their permissions, and I'm more surprised that more files weren't modified by this operation.

 Default project location was set to root, and I have some issues with permission. I should probably move the project somewhere else. ECS fixing doesn't work without write access. 

I have no idea currently how to safely ignore changes to those files, without reverting others.

File: backend/Exceptions/SimpleMessageException.php (hunk 7 above)
Comment (plencka) [reply backend/Exceptions/SimpleMessageException.php:19]: I think that maybe keeping error codes this way would be useful in the future. 

It's some form of standard and maybe in the future somebody would like to implement database to the project with Admin panel. Files with .csv extension were intended to be easy to modify. Maybe there will be a form in the future to add/modify company entries and errors could be thrown there?

I still need to properly assign error codes to the Exception as per Kamil's suggestions, because I'm not familiar yet which responses would be best in those scenarios.

**Review by mtracz — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]

**Review by brzozka — APPROVED** [review]
